### ISSUE TITLE
worksheetOrder() keeps original first worksheet and new first worksheet selected

### ISSUE THREAD

**Issue by jmbarbone** [ycphs/openxlsx#102]
**Describe the bug**
When reordered worksheets, if the new order changes the first worksheet, both the original first sheet and the new first sheet are selected when opening the workbook.

**To Reproduce**
```r
wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
addWorksheet(wb, "Sheet2")
addWorksheet(wb, "Sheet3")

# Issue also present after saving and loading
# tempf <- tempfile(fileext = ".xlsx")
# saveWorkbook(wb, tempf)
# loadWorkbook(tempf)

worksheetOrder(wb) <- c(2, 3, 1) # Set first sheet to Sheet2
openXL(wb) # Both Sheet2 and Sheet1 are active/selected
```
From there if you being to type anything you can see the values are entered into both Sheet2 and Sheet1

**Versions**
 - openxlsx 4.2.2
- R 4.0.2

**Comment by cwolcott** [comment]
I am seeing the same thing.

**Comment by ycphs** [comment]
this problem should be solved now too

**Comment by cwolcott** [comment]
No there are still issues with calling worksheetOrder(wb) <- ....

This is the workbook without performing any calls.  The first worksheet is active.
<img width="654" alt="Workbook v01 basic" src="https://user-images.githubusercontent.com/3777526/113929177-bff43d80-97bd-11eb-87b3-9370fe572678.png">

Next I added the call worksheetOrder(wb) <- c(4, 1, 2, 3) to move the 4th tab to the front. You can see the issue.
The 4th tab did move to the front, but now worksheet 1 and 2 are active, instead of worksheet 2 the original active sheet.
<img width="654" alt="Workbook v02 worksheetOrder" src="https://user-images.githubusercontent.com/3777526/113929348-f631bd00-97bd-11eb-8f20-e1699a7b7dac.png">

I then combined the two calls, hopeing that would clear things up, but the answer is no.
    worksheetOrder(wb) <- c(4, 1, 2, 3)
    activeSheet(wb) <- 'Configuration'
<img width="654" alt="Workbook v03 activeSheet" src="https://user-images.githubusercontent.com/3777526/113929806-76582280-97be-11eb-9025-f2b0ab2dec46.png">
Not sure what is happening now.  Why did the Raw sheet become active with Configuration and MeanTemp is no long active.

**Comment by ycphs** [comment]
Thank you for the tests.

PR #171 

Should fix the issue

**Comment by jmbarbone** [comment]
Closing as I don't see the issue anymore.
