### ISSUE TITLE
Error when saving Workbook containing grouped rows

### ISSUE THREAD

**Issue by namarkus** [ycphs/openxlsx#138]
**Describe the bug**
Loading an existing Excel file that contains some rows that are grouped and saving it leads to the following error message:.

> Error in write_worksheet_xml_2(prior = prior, post = post, sheet_data = ws$sheet_data,  : 
>   CHAR() can only be applied to a 'CHARSXP', not a 'NULL'
> 

**To Reproduce**
File containing 1 sheet with small data and some rows are grouped:
[has_grouped_rows.xlsx](https://github.com/ycphs/openxlsx/files/5879375/has_grouped_rows.xlsx)

**Fails**:  Load existing workbook that contains grouped rows and save it:
```
library(openxlsx)
wb = loadWorkbook("has_grouped_rows.xlsx")
saveWorkbook(wb, file="has_grouped_rows_out.xlsx")
```

**Works**: ungroup rows prior to saving workbook
```
wb = loadWorkbook("has_grouped_rows.xlsx")
ungroupRows(wb, 1, 1:20)`
saveWorkbook(wb, file="has_grouped_rows_out.xlsx")
```

**Works**: ungroup rows and group again prior to saving workbook
```
wb = loadWorkbook("has_grouped_rows.xlsx")
ungroupRows(wb, 1, 1:20)
groupRows(wb, 1, 2:11)
saveWorkbook(wb, file="has_grouped_rows_out.xlsx")
```

**Desktop:**
tested on two different systems with identical behavior:

System 1:
 - Windows 10
 - Excel Version: Microsoft Excel for Windows 365 MSO (16.0.13328.20476) 64-Bit
 - R Version: R4.0.2
 - openxlsx: 4.2.3

System 2:
 - Windows 10
 - Excel Version: Microsoft Excel for Windows 2016 MSO (16.0.13530.20418) 64-Bit
 - R Version: R4.0.3
 - openxlsx: 4.2.3

**Additional context**
This problem does not apply to grouped columns, workbooks containing grouped columns can be saved without problems.

**Comment by JanMarvin** [comment]
likely an import bug. when writing the c++ function is expecting a character but gets a null.

**Comment by JanMarvin** [comment]
Had a quick look. After the import `outlineLevels` does not have a filled `hidden` attribute. Since most of the writing stuff in `openxlsx` happens with whatever is imported, the error is caused by the c++ function expecting a character vector of `length(outlineLevels)`.

Possible fixes are 0) fix the import to provide the required `hidden` attribute, 1) adding a hidden row, if any `outlineLevels` is imported or 2) fix the c++ function to check if hidden is a `character(0)`. For the time being I suggest 1) which could be done using an lapply function (but I wont write this pull request atm, I'm dropping out of this issue). The entire reason of this issue is somewhat related to #81, `openxlsx` has known issues with the import of certain style attributes. 

```R
> library(openxlsx)
> 
> fl <- "/tmp/has_grouped_rows.xlsx"
> wb = loadWorkbook(fl)
> 
> # # spot the differences
> # ungroupRows(wb, 1, 1:20)
> # groupRows(wb, 1, 2:11)
> # 
> # wb$outlineLevels
> 
> wb$outlineLevels[[1]]
  2   3   4   5   6   7   8   9  10  11 
"1" "1" "1" "1" "1" "1" "1" "1" "1" "1" 
attr(,"hidden")
character(0)
> attr(wb$outlineLevels[[1]], "hidden") <- rep("0", length(wb$outlineLevels[[1]]))
> 
> saveWorkbook(wb, file="/tmp/has_grouped_rows_out.xlsx", overwrite = T)
> 
```
