### ISSUE TITLE
Writing certain text (unicode I suppose) corrupts the file

### ISSUE THREAD

**Issue by aavanesy** [ycphs/openxlsx#152]
**Describe the bug**
See code. For some reasong if a text contains '\037' it will write but not open the file.
I haven't tested other strings but this is I suppose some unicode issue.

**To Reproduce**
```wb <- openxlsx::createWorkbook()
text = 'abcd\037'
openxlsx::addWorksheet(wb, 'Data')
writeData(wb, 'Data', text, startRow = 1)
saveWorkbook(wb,'file3.xlsx', overwrite = T)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - R 4.02
 - Openxlsx 4.2.3

**Additional context**

**Comment by bryburgess** [comment]
Same issue on MacOS 11.2.3, R 4.02, Openxlsx 4.2.3. 

I tried writing a list of tibbles and keep encountering the string error. All the tibbles have characters in the first col, and the rest are numeric with a mix of NAs/values. Excel won't open the file without force-fixing it, which just ends up stripping the column names, first character column, and the explicit NAs from the data. 

**Screenshot**:
<img width="711" alt="Screen Shot 2021-06-04 at 2 26 35 AM" src="https://user-images.githubusercontent.com/85198735/120755769-69b12b80-c4dc-11eb-8ccf-c9025b358998.png">

**Excel error message:**

> 
> > <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to sectors_donors_snapshots_160.xml</logFileName><summary>Errors were detected in file '/Users/bryan/Documents/sdg/imf_cd_size_of_prize/data/data_for_export/sectors_donors_snapshots_16.xlsx'</summary><removedParts summary="Following is a list of removed parts:"><removedPart>Removed Part: /xl/sharedStrings.xml part with XML error.  (Strings) Xml parsing error Line 1, column 5330.</removedPart></removedParts><removedRecords summary="Following is a list of removed records:"><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet1.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet2.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet3.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet4.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet5.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet6.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet7.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet8.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet9.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet10.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet11.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet12.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet13.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet14.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet15.xml part</removedRecord><removedRecord>Removed Records: Cell information from /xl/worksheets/sheet16.xml part</removedRecord></removedRecords></recoveryLog>


Edit: Individual tibbles write fine, the issue seems to be in the list... Though the sheet names and numeric values write correctly. Setting the declared encoding for the colnames and first variable to UTF-8 doesn't seem to help either.

**Comment by JanMarvin** [comment]
Hi @aavanesy , thanks for the report and sorry it took so long to response. The issue is that your input is invalid. Whatever gave you this input, included the [unit separator `\037`](https://www.ascii-code.com/) from ascii. Therefore now you pass a zero terminated string to `openxlsx`. In R it looks like this (the question mark is invisble in R):
```R
> text = 'abcd\037'
> message(text)
abcd
```

`openxlsx2` creates `<si>abcd\037</si>` from your input, which is not valid XML. In XML you would have to escape it like this: `<si><t>abcd&#31;</t></si>`. Presumably you do not even want this in your code after all:

```R
> stringi::stri_replace_all_fixed(text, "\037", "")
[1] "abcd"
```

Even though this barked at you in the xlsx file, it is more an issue of the input. We sure should remove it or escape it, but that is just one of the many occasions where the user might provide us with broken input that we cannot really control.
