### ISSUE TITLE
No updated formula when write/read workbook

### ISSUE THREAD

**Issue by fcebron2106** [ycphs/openxlsx#188]
I have an existing workbook ("ex.xlsx"), with 2 sheets.

- A sheet named "donn"
- A sheet named "result", with a formula in cell A2 = donn!A2.

With R code, I put a value (10) in the cell A2 of the "donn" sheet. And I save the file.

```
file = "ex.xlsx"
savedFile" = ex2.xlsx"

wb = openxlsx::loadWorkbook(file)
openxlsx::writeData(wb,"donn", startRow = 1, startCol = 2, x= 10)
openxlsx::saveWorkbook(wb, savedFile, overwrite = TRUE)
```

When I read the new file with R, the cell A2 of the sheet "result" is not equal to 10.

`
data = openxlsx::read.xlsx(savedFile, "result", colNames = FALSE)`

It seems that, when the workbook is saved with R, the formula are not updated.

If I open the file savedFile.xlsx with Excel, save it and then try to read it again with R, the cell A2 of the result sheet is equal to 10.0.

 - OS: Windows10
 - openxlsx version : 4.2.3

**Comment by JanMarvin** [comment]
Yes. this is correct. Basically if you want the formula to be updated, you have to open the file with Excel and save it. In addition, I'd recommend whenever you're opening Excel sheets with formulas, you should open and save them with Excel prior to the import.

The following is happening: 

1) The first input you open has both sheets and presumably was written with Excel. The cell with the formula has the correct value. This value is stored as the underlying value field of the formula inside the xlsx file. You can think of this as some kind of cache value, so that Excel does not have to update this cell all the time when opening the file.

2) Now you modify the file in `openxlsx` and change the input for the formula. This does not update the cached cell with the formula. For this to work, someone would have to implement every possible formula and quirks Excel provides. This might be easier for `=SUM()` but think of `=VLOOKUP()` etc or formulas where R and excel produce different results (starting with `round`). Basically if you want to have this, you'd have to reimplement Excel in R.

So that's what happens and that's why this most likely will not be implemented ever. The bad part for the user is, there is no way to tell which formulas have been evaluated and cached in Excel. Which is why my initial statement is you should open and save every xlsx file before you start to import it.

**Comment by nathanckuhn** [comment]
I've been seeing, I believe, the same problem. And I think there is a solution, I just currently don't know how to implement it.
I was going to create my own issue, but I'll post this here:

First, thank you to all who have worked on this package! I use it a lot in my workflows. 
One complicated workflow I have creates a complex Excel file using openxlsx, writes it out as an Excel file (to be used elsewhere), and then that Excel file created by openxlsx is read back into R as a data frame.

The Excel formulas do not read back into R correctly (as in, they are not read in at all). 

I believe the problem is due to something missing in the openxlsx XML map of Excel.

Forgive me if the below if too detailed, but this is how I came to this conclusion, and it may help newer R users (like I still am).

---------------------

Part 1: Here is a reprex that can be run to create & test files:

```
library('fs')
library('here')
library('openxlsx')
library('readxl')
library("KeyboardSimulator")

### Rename test folder as desired.
test_folder_name <- "local_tests"

### Create folder if does not exist.
fs::dir_create(here::here(test_folder_name))

test_path_1orig <- here::here(test_folder_name, "test_1orig.xlsx")
test_path_2edit <- here::here(test_folder_name, "test_2edit.xlsx")

#################################  ##  
### Use Example from writeFormula() Help to create workbook "wb" object with Excel formulas:
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, "Sheet 1")
openxlsx::writeData(wb, "Sheet 1", x = iris)
v <- c("SUM(A2:A151)", "AVERAGE(B2:B151)") ## skip header row
openxlsx::writeFormula(wb, sheet = 1, x = v, startCol = 10, startRow = 2)
openxlsx::writeFormula(wb, 1, x = "A2 + B2", startCol = 10, startRow = 4)

#################################  ##  
### Write out workbook twice. 
openxlsx::saveWorkbook(wb, test_path_1orig, overwrite = TRUE)
openxlsx::saveWorkbook(wb, test_path_2edit, overwrite = TRUE)

### Excel functions not resolving when read back into R with readxl. Expected formula result numbers not seen in column 10 (J2:J4).
test_1orig_readxl <- readxl::read_excel(test_path_1orig)
View(test_1orig_readxl)

### Same issue if read in with openxlsx. Formulas not resolving (in fact, row 10 completely ignored).
test_1orig_openxlsx <- openxlsx::readWorkbook(test_path_1orig, skipEmptyRows = FALSE, skipEmptyCols = FALSE)
View(test_1orig_openxlsx)

#################################  ##  
### Open 2nd originally-identical file with Excel & see that functions DO work when opened in Excel.
file.show(test_path_2edit)
Sys.sleep(7)
### The most minimal "Edit" & Save in Excel. Editing-and-Saving to see if the Excel program changes the file.
KeyboardSimulator::keybd.press('f2')
KeyboardSimulator::keybd.press('enter')
KeyboardSimulator::keybd.press('ctrl+s')
Sys.sleep(7)
### Close Excel. 
### WARNING! This will close ALL Excel files open.
system("taskkill /IM Excel.exe")
Sys.sleep(7)

### Read in the file that has now been edited & re-saved.
### Now formulas read in correctly --- only after editing & re-saving in Excel.

test_2edit_readxl <- readxl::read_excel(test_path_2edit)
View(test_2edit_readxl)

test_2edit_openxlsx <- openxlsx::readWorkbook(test_path_2edit, skipEmptyRows = FALSE, skipEmptyCols = FALSE)
View(test_2edit_openxlsx)

### Something seems missing in the openxlsx xml map of Excel.
```

---------------------

Part 2: Investigate the files' XML.

I did this trying to understand what the Excel program does to the file after editing-and-saving:
1.	Make copies of files "test_1orig.xlsx" and "test_2edit.xlsx"
2.	Change the file extension to ".zip" for each copied file to get "test_1orig.zip" and "test_2edit.zip"
3.	Unzip/extract each .zip file to get two folders "test_1orig" and "test_2edit"
4.	Search each unzipped folder for "calcChain".

In folder "test_1orig", "calcChain" is not found.

In folder "test_2edit", "calcChain" IS found 6 times across 3 files:

In folder "test_2edit/xl", this document was new: "test_2edit/xl/calcChain.xml". Here is the entire file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<calcChain xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<c r="J4" i="1" l="1"/><c r="J3" i="1"/><c r="J2" i="1"/>
</calcChain>
```

In document "test_2edit/[Content_Types].xml" this phrase was new:
```
<Override PartName="/xl/calcChain.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.calcChain+xml"/>
```

In document "test_2edit/xl/_rels/workbook.xml.rels" this phrase was new:
```
<Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/calcChain" Target="calcChain.xml"/>
```

There are numerous XML differences between the two Excel files (one of which was opened and resaved in the Excel program). 
To me, it seems that "test_2edit.xlsx" having "calcChain.xml" and the associated references may be the key difference.

If this is the key difference, could it be incorporated into openxlsx? 
And would that solve the problem of formulas not resolving?

---------------------

Part 3: I also tested if the "wb" object created by openxlsx could just be changed into a data frame, hoping that would solve the formula problem.

Answer: Yes, object "wb" can be turned into a data frame, but no, none of the Excel formulas resolve when this is done.

```
### Continue code from reprex above:
### Neither of these functionally identical functions recognize/read in the formulas in column 10. 

df_wb1 <- openxlsx::read.xlsx(wb, skipEmptyRows = FALSE, skipEmptyCols = FALSE)
df_wb2 <- openxlsx::readWorkbook(wb, skipEmptyRows = FALSE, skipEmptyCols = FALSE)

View(df_wb1)
View(df_wb2)

### So, openxlsx can turn a wb back into a data frame, but Excel formulas do not resolve when that happens.
```

If the openxlsx XML were adapted to include "calcChain.xml" and associated references, could that also fix this related problem?
(This might need it's own ticket.)

---------------------

I am still a beginner at much of R, and the source code for openxlsx is currently beyond me, so I do not know how to suggest changes to openxlsx's XML code.

For those that maintain this package, would these suggested XML changes work?

Thank you for your consideration and again for all the work already put into this package.

**Comment by JanMarvin** [comment]
Hi @nathanckuhn and thank you for your kind words.

Please see my comment above. There are still certain features unsupported in openxlsx and this calcchain.xls file is among them (I assume it's just some log for Excel which cells are connected, e.g. if one is updated, how many others have to be updated), but there is no way that once we can write this file ourselves, that formulas will be evaluated in some "magical" way.

Excel formulas are little programs. Just like little R scripts. These formulas can be evaluated by software (Excel, Libreoffice, Google Sheets, this Apple calc one and others), but this requires to write a software that does exactly that. Just like R scripts are evaluated by R and if they are opened in Notepad contain only some text input.

**Comment by nathanckuhn** [comment]
@JanMarvin , sorry for a slow response, but thank you for your thoughts on this & other threads.
