### ISSUE TITLE
write.xlsx does not error if it doesn't have write permissions

### ISSUE THREAD

**Issue by jeff-m-sullivan** [ycphs/openxlsx#190]
**Describe the bug**
If `write.xlsx` is asked to write out data to a file that the user doesn't have write permissions to, it fails silently.

**To Reproduce**
```
> fs::file_create("foo.xlsx", mode="a=rx")
> openxlsx::write.xlsx(x=cars, file="foo.xlsx", overwrite=TRUE)
```

**Expected behavior**
It should throw an error, like `write.csv` does:

```
> fs::file_create("foo.csv", mode="a=rx")
> write.csv(cars, file="foo.csv")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'foo.csv': Permission denied
```

This was using the latest CRAN version: 4.2.3

**Comment by ycphs** [comment]
Please try the parameter `returnValue`

[Additional parameters](https://ycphs.github.io/openxlsx/reference/saveWorkbook.html)

**Comment by jeff-m-sullivan** [comment]
Thanks for the suggestion, but it yields the same output whether or not the write operation is successful:

```
> fs::file_create("foo.xlsx", mode="a=rx")
> (openxlsx::write.xlsx(x=cars, file="foo.xlsx", overwrite=TRUE, returnValue=TRUE))
A Workbook object.
 
Worksheets:
 Sheet 1: "Sheet 1"
 

 
 Worksheet write order: 1> 
> (openxlsx::write.xlsx(x=cars, file="foo2.xlsx", overwrite=TRUE, returnValue=TRUE))
A Workbook object.
 
Worksheets:
 Sheet 1: "Sheet 1"
 

 
 Worksheet write order: 1> 
```

Here are the two files:
```
Downloads % ls -l foo*
-r-xr-xr-x  1 localjeff  staff     0 May 11 14:53 foo.xlsx
-rw-r--r--  1 localjeff  staff  6742 May 11 14:54 foo2.xlsx
```

**Comment by jmbarbone** [comment]
`write.xlsx()` doesn't seem to use the `returnValue` parameter for `saveWorkbook()`.  There would also be a bit of a weird value return since `write.xlsx()` also returns the `Workbook` object (this could be changed after #194 since generating the `Workbook` could be done separately from saving).

This is an issue with `saveWorkbook()`: 

https://github.com/ycphs/openxlsx/blob/master/R/wrappers.R#L122-L134 

There's a `tryCatch()` wrapped around the `file.copy()`.  I don't know if that's necessary.  I would expect that if the file doesn't copy (ie, save) then the function should fail.
