### ISSUE TITLE
Feature Request - function to set Print area for multipage sheet

### ISSUE THREAD

**Issue by AlvaroMCMC** [ycphs/openxlsx#235]
recently I'm using this excel functionality very much: print area for multipage sheet (A3 size) like this:

![image](https://user-images.githubusercontent.com/21317475/127388859-efb141ce-7992-4dbd-be0a-9b6fcced5912.png)

So It would be awesome to have this in openxlsx.

**Comment by ycphs** [comment]
There is already a PR #223 covering the topic of named regions.

As far as I looked into the details, printing areas are just named regions. It would be great, if you could contribute to the existing pull request.

**Comment by AlvaroMCMC** [comment]
In fact, I'd like to contribute, What knowledge do I need to have to do that?

**Comment by JanMarvin** [comment]
The project consists of R, XML and C++ code. However, to fix small things, basic R knowledge should be enough. Unfortunately, many ideas/requests are often not small requests :smile: . For many requests, it is crucial to find the required XML nodes to add to the XML files. For example, to implement a feature like the ones you've requested recently:

1) You would first need to research how the XML structure expected by Excel looks like, for example, by studying files written by Excel (create a file that provides the feature and compare it to a file that does not). 
2) Next, you have to study the `openxlsx` code base where the required implementation can be entered.
3) Write or modify a function that creates the XML code and add it to the output.
4) Write tests that verify that the added function works as intended.

In many cases, 1) is the hardest task, as it can be quite time consuming to research what precisely Excel expects.

If you want to contribute to your feature requests, it would be helpful if you could provide the research or sample files. But please keep in mind that not every feature requests is high priority for us, and with low priority feature requests, chances are that no one has the time to pick up the ball to develop something that might be requested by maybe only a single user (even if samples are provided). That's not because of disrespect of the user, but we are developing for fun in our free time, and spending many hours after work researching and implementing things we do not need is, well, unlikely.

**Comment by namtranhoang1992** [comment]
I think this SetPrintArea functionality is useful. I would be happy to help with researching to make this functionality. I need some pointers of how I can start though: how to I study the structure of an .xlsx file? I tried opening .xlsx with notepad, to no avail.
I know R, VBA, and basic C++. I can try to read codes of various programming languages.

At work, since my bosses only use .xlsx and .pdf; I use a work-around: 
1. using R to export data
2. using excel VBA to set print area
3. from excel with print area, we can get to .pdf

Useful VBA codes to look up if you are interested: 
ActiveSheet.PageSetup.PrintArea = "A1:C3"
ActiveSheet.ExportAsFixedFormat Type:=xlTypePDF, Filename:=FileNameVar _
        , Quality:=xlQualityStandard, IncludeDocProperties:=True, IgnorePrintAreas _
        :=False, From:=Loop_Variable, To:=Loop_Variable, OpenAfterPublish:=False

**Comment by JanMarvin** [comment]
Hi @namtranhoang1992 , you can open any xlsx file with any zip tool like 7zip or Linux utils or simply `unzip( file, exdir = ".")`. The xlsx file consists of multiple XML files.
