### ISSUE TITLE
Update news for release

### ISSUE THREAD

**Issue by ycphs** [ycphs/openxlsx#242]
@JanMarvin @jmbarbone @jeff-m-sullivan 

Could you please update the NEWS for the up coming CRAN release?

**Comment by jmbarbone** [comment]
PRs that I've submitted should have included notes in `NEW.md` but I'll take another look through to make sure none was missed

**Comment by jmbarbone** [comment]
@JanMarvin You've been quite busy, can you take a look at these issues/PRs?  I don't think they were included in the `NEWS`.  This was a quick search, can't guarantee this is all of them since the previous release?

| Issue | PR |
|-|-|
| #228 | #237 |
| #114 | #113 |
| #112, #116, #204 | #225 |
| #200, #212 | #203 |
| #201 | #202 |

**Comment by JanMarvin** [comment]
I'll have a look later. I assume there are a few fixes not mentioned in the NEWS file for the current release, those for the upcoming release should be fine.
