### ISSUE TITLE
Excel output has non-standard column widths

### ISSUE THREAD

**Issue by xIncubakerx** [ycphs/openxlsx#323]
When you create an excel spreadsheet using this package, the excel spreadsheet that is output has a column width of 10.71 rather than the excel standard of 8.43. The following code creates a basic example of this with an empty spreadsheet.
```
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, "Sheet 1")
openxlsx::saveWorkbook(wb, "Test.xlsx", overwrite = TRUE)
```

I would expect the default column width to be 8.43 in the excel output, as this is the standard excel column width. Indeed, ```setColWidths``` suggests that the default width should be 8.43 as follows:
```
setColWidths(
  wb,
  sheet,
  cols,
  widths = 8.43,
  hidden = rep(FALSE, length(cols)),
  ignoreMergedCells = FALSE
)
```
While I can use ```setColWidths``` to change the column width back to 8.43, I can only do this for my dataframe and any blank cells off to the right will remain as 10.71 width.

**Comment by deschen1** [comment]
I can confirm the issue.

**Comment by JanMarvin** [comment]
Interesting. I checked the value a few days ago and had the impression that 10.71 was the default, but was tricked by openxlsx :-)
Should be a simple fix

**Comment by JanMarvin** [comment]
Unfortunately the latter didn't prove to be true. It's not a simple fix or at least not as simple as I'd hoped. 

Here the initial colwidth is set:
https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/worksheet_class.R#L70

But here
https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/workbook_column_widths.R#L21
here
https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/workbook_column_widths.R#L133
and here
https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/workbook_column_widths.R#L145
`0.71` is added. Removing this and changing it to 0.43 and basecolWidth 8 did not work for me. The test barked. When saving or loading the values were changed. Unsure why also unsure I wanna find out :see_no_evil:

**Comment by deschen1** [comment]
Is there a reason why the base column width is defined as 10 (or 8 for that matter) and then 0.71 is added at different places (not that it would solve the problem at hand)? Wouldn't it be more straightforward to directly define 8.43 as default width? (I'm obviously not deep enough into the code, so sorry if I probably miss some important reasons).

**Comment by xIncubakerx** [comment]
I'm guessing that `baseColWidth` has to be an integer? I had the same thought as deschen, it seems odd that there is a base width that has to be modified at a later stage. But if it doesn't have to be an integer and for whatever reason we have to keep adding on the 0.71 later, I wonder if you could see the base width to 7.72 and get there through slightly dodgy means 🤣

**Comment by JanMarvin** [comment]
The reason is: it's a quite complex spaghetti code 😉 
Tbh I have no clue. Might be due to some interaction with calculate column widths or load workbook.
[Edit:] if you want to help figuring it out, be my guest. It's one of the many "seems like a simple fix and waste countless hours fixing something unimportant" issues. I tried, I failed, I invest my time elsewhere.

**Comment by xIncubakerx** [comment]
I probably don't have a strong enough coding background to fix this one either unfortunately 😢

**Comment by deschen1** [comment]
Yea, same here. I have some basic understanding of what I'm doing in R, but finding the bug in the package is beyond my paygrade, I'm afraid. However, I scanned through the code and found another one where a width of 9.15 is set. NOt sure, though if that's causng the issue:

https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/workbook_column_widths.R#L136

There's also this function here that seems to calculate the column widths based on the character lengths. Is started digging into where thsi function comes from and it pops up in the RcppExports.R file, but there it immediately calls another function in a way I don't understand, so I stopped there. But maybe that gives some hints as to where to look. 🤷 

https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/workbook_column_widths.R#L122

**Comment by JanMarvin** [comment]
ah thanks, at least that gives another hint. I'll look into that over the weekend. If you want to, clone the package, open the project in Rstudio. do some changes and hit "install and restart", wait a moment and run the tests to see if it works. Nobody was born a coder and we all started sometime with a minor change (and we're here to help; within limited range ofc)

**Comment by deschen1** [comment]
OK, I'm completely confused now. So I did download the package and tried to find whereelse teh column width is set. I found a few more instances where I only see the `0.71` parts, also in some of the C++ files.

Then I stumbled upon one thing in the `wrappers.R` file (lines 1277ff.) where I actually do see a 8.43, but nowhere else. In that area, there's some re-calculation with pixels - I don't understand it, so I googled.

I then came scross this one page here that says "In Excel2003 the width of a column by default is 8,43 characters or 10,71 points.": http://www.teacherclick.com/excel2003/t_7_2.htm

So I had some hope and thought, oh maybe it's all correct after all, maybe we just talk about different units. But then I opened Excel and started typing in a few characters, because I thought in a standard cell would now fit ~8.43 characters. Guess what? It's roughly about 10.71 characters fitting into a cell, not 8.43. So that doesn't seem to be the solution.

I also came across this page where there's an explanation on how to calculate column widths in Excel: https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2010/cc802410(v=office.14)?redirectedfrom=MSDN i'm just parking it here, because maybe it is helpful for these calcualtions in the `wrappers.R` file.

Did some more googling, but also MS is saying 8.43 should be correct: https://support.microsoft.com/en-us/office/change-the-column-width-and-row-height-72f5e3cc-994d-43e8-ae58-9774a0905f46

BUT, it says it's 8.43 on a point scale. It doesn't say that it's 8.43 characters. So maybe this link above that said "8.43 chars or 10.71 points" is wrong and it is exactly the other way around.

But then I opened Excel online, where the standard width indeed is 8.43 and it says "standard units" and the mouseover is that this is the number of characters that can be shown with a standard setting.

And finally, I also just opened a blank Excel file and while I'm kind of 90% sure that I previously saw that the column width is 8.43, it is now 10.71.

So at this point, I'm more confused than before, but hope I could contribute at least sth. to the problem solving.

UPDATE: oh, one more link:

https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-column-widths

So this one sounds like it totally depends and the 8.43 were normal in old Excels with Arial 10pt. But nowadays we have Calibri 11pt, which might explain the difference. This link btw also talks about thsi weird thing, where Excel starts with an integer base width (8 or 10) and then adds to it.

BTW, a colleague of mine also has Calibri 11pt, but a standard width of 8.26 for whatever reason.

**Comment by JanMarvin** [comment]
Thanks @deschen1 , I'll look into it sometime soon. We are doing something wrong here, but at least we are doing it wrong for a long time and nobody complained. Consistency is key. It's just low priority, because there are more important things to fix and apparently it's not a simple fix

**Comment by xIncubakerx** [comment]
I can appreciate that this is a lower priority fix, but thanks for looking into it anyway @JanMarvin. Found this post from a year and a half ago, which might be useful, but I'm not really too sure what is going on (I'm pretty new to R in general).
https://github.com/ycphs/openxlsx/pull/91

**Comment by tobwen** [comment]
I know this has been closed, but I've tested it on 37 machines with Excel 2010 and Excel 365 (we're running both for complicated reasons): `10.71` is default here.

MAYBE it's a localized thing?! I've tested it with the **German** locale!
