### ISSUE TITLE
Files should be written according to default ACLs

### ISSUE THREAD

**Issue by finalspy** [ycphs/openxlsx#333]
Expected Behavior

Files should be written using the system acls
Actual Behavior

For example it works properly with writexl package,
But it doesn't using openxlsx.
Need to set Sys.umask("0007") in .Rprofile in my case to have proper acls
Steps to Reproduce the Problem

(please attach an example xlsx file if possible)

    Mount an NFS directory with specific acls

    Make a script to write an xls file to this directory

    Check the file rights

sessionInfo()

    Version of openxlsx: `4.2.5.9000`
    Version of R: `4.1.1`

I don't know if this is linked to the NFS mount but I prefer to mention this specificity.
What seems odd to me is that the behaviour is different from writexl and openxlsx.
The former one seems right ...

Here's a file with right acls written with writexl package :

library(writexl)
cars <- mtcars[1:6, ]
write_xlsx(x = cars, path = "test_writexl.xlsx", col_names = TRUE)

Here's another script with wrong acls with openxlsx package :

library("openxlsx")
wb <- createWorkbook()
cars <- mtcars[1:6, ]
addWorksheet(wb, "Cars")
writeData(wb, "Cars", cars, startCol = 2, startRow = 3, rowNames = TRUE)
saveWorkbook(wb, "test_write_openxlsx.xlsx", overwrite = TRUE)

Here are the results :

-rw-------  1 myuser test-projet 6875 Mar  2 19:22 test_write_openxlsx.xlsx
-rw-rw-rw-  1 myuser test-projet 5438 Mar  2 19:23 test_writexl.xlsx

And here are the ACLs for my current directory on the NFS server :

user::rwx
group::---
group:test-projet:rwx
other::---
default:user::rwx
default:group::---
default:group:test-projet:rwx
default:other::rwx

And here are the ACLs on the mounted directory (same directory but client side)

user::rwx
group::rwx
other::

**Comment by JanMarvin** [comment]
I've been a linux user for 15-16 years now, but haven't come across NFS. I assume there is no simple way for us to test this. Nor - to be honest - do I have any clue how we could. Since we do not write files ourself, but instead write to some temporary directory which is zipped afterwards, could you check if the same thing happens with the `zip` package? (We use it to create the xlsx output.)

https://github.com/ycphs/openxlsx/blob/9223f05791cc139e27d158e50ea80677e9ee0d9b/R/WorkbookClass.R#L1083-L1088

**Comment by finalspy** [comment]
I've been able to make new tests on basic filesystem, not on NFS mounted directories, I simply created a folder where my user can write on the FS outside the NFS mounts.

The file is still written with `rw-------` rights with **openxlsx** but `rw-rw----` with **writexl**.

So this is not linked to NFS mount as far as I understand it.


Moreover I tested to write a zip file as you suggested using zip::zipr and the rights are OK : `rw-rw----`

**Comment by JanMarvin** [comment]
Cannot reproduce on both of my Arch system. Maybe you're system inherits the access rights from `/tmp`?

```R
> # openxlsx
> library(openxlsx)
> wb <- createWorkbook("Creator of workbook")
> addWorksheet(wb, sheetName = "My first worksheet")
> saveWorkbook(wb, file = "saveWorkbookExample.xlsx", overwrite = TRUE)
> substr(system("ls -l saveWorkbookExample.xlsx", intern = TRUE), 1, 10)
[1] "-rw-r--r--"
> 
> # base
> write.csv(mtcars, "mtcars.csv")
> substr(system("ls -l mtcars.csv", intern = TRUE), 1, 10)
[1] "-rw-r--r--"
```

**Comment by finalspy** [comment]
Does your target folder has special ACLs ? 
Mine are set like this  in shell : 
```
sudo mkdir /target_folder
sudo chgrp nobody /target_folder
sudo chown my_user /target_folder
sudo setfacl -m u::rwx,u:ssh_user:rwx,g::---,g:admin_group:rwx,o::--- /target_folder
sudo setfacl -d -m u::rwx,u:ssh_user:rwx,g::---,g:admin_group:rwx,o::--- /target_folder
```

where 

- `target_folder` is where I want to write,
- `my_user` is my user 
- `ssh_user` is another user that should have rights on the folder through acls
- `admin_group` is a group that should be able to access the folder 

my system umask is set to 0077 but this should not interfere according to the default ACLs set previously.

**Comment by JanMarvin** [comment]
No I don't, I'm sorry but if you want me to research this, please create a simple example. Your code does not work for me and after a busy day I can't say that I'm in the mood to research why ;-)

```
...
sudo setfacl -m u::rwx,u:ssh_user:rwx,g::---,g:admin_group:rwx,o::---target_folder          
setfacl: Option -m: Invalid argument near character 10
```

If the issue persists, you can wrap the `saveWorkbook()` function and a call to `chmod`. Not beautiful, but better than nothing.

```R
> saveAndChmod <- function(wb, file = "saveWorkbookExample.xlsx", overwrite) {
+   saveWorkbook(wb, file, overwrite)
+   system(paste("chmod 666", file))
+ }
> 
> wb <- createWorkbook("Creator of workbook")
> addWorksheet(wb, sheetName = "My first worksheet")
> saveAndChmod(wb, file = "saveWorkbookExample.xlsx", overwrite = TRUE)
> substr(system("ls -l saveWorkbookExample.xlsx", intern = TRUE), 1, 10)
[1] "-rw-rw-rw-"
```

**Comment by finalspy** [comment]
I have workarounds : for example setting `Sys.umask(0002)` in the `.Rprofile` for instance.
What annoys me is that the behavior is different with other packages like writexl. 

I'll try to find some times to create a full example maybe with a docker file or so to have the right users /groups etc available.

**Comment by JanMarvin** [comment]
> What annoys me is that the behavior is different with other packages like writexl.

Sorry, but this is a voluntary open source project. If this special behavior you desire does not work the way you want to, you could research the problem, discuss your findings, prepare a pull request and if we agree on the solution, we'd be happy to apply it. Saying "this one extra line in `.Rprofile` annoys me" isn't going to make me invest any more time in _your_ very specific issue.

Since you've brought it up a few times: If other projects serve your needs better, please go ahead and use them. We are not holding you back, but we are also not payed software engineers to work on "exotic" problems to please our not paying customers nor do we necessarily share a desire to unify behavior across R packages. To quote the MIT license: 'THE SOFTWARE IS PROVIDED "AS IS"'.

**Comment by finalspy** [comment]
... i'm speechless ... sorry if I irritated you that wasn't my purpose ... 
I don't really understand your reaction.

Maybe my words weren't wisely choosen as i'm not fluent in english. Should I have said  "bothers me" or "bores me" instead of "annoys me" ? 
What I meant was just that "it seems strange to me that openxlsx has a different beahaviour".

I don't think that not respecting special ACLs is so exotic (I admit NFS can be).

I'm here to point out a possible issue and help solve it. May be you could just point me on how this is done or if there are some specific design in your lib that could explain the anormal (to me) behaviour. 

As you have noticed I'm not just complaining but take several hours testing and trying to find ways to understand the problem and make it reproducible.
I even found a workaround I shared with you and the community in case someone else ran into the same issue.

 I'm not the one using the script, I'm not the one choosing those tools, I just noticed this problem someone else told me about, I'm neither a R user nor an R developer, so please be kind also.

**Comment by finalspy** [comment]
To move forward on more constructive consideration, I read the code of https://github.com/ycphs/openxlsx/blob/master/R/WorkbookClass.R
As far as I understand it (disclaimer I'm not an R nor cpp developer) the file is first created in a temporary directory (https://github.com/ycphs/openxlsx/blob/master/R/WorkbookClass.R#L563)
My guess is that the file inheritates the ACLs from this temporary directory and keep it upon copy to final destination. does this make any sense ? (I'll try to test my assumption by my self)

**Comment by JanMarvin** [comment]
Hi @finalspy , sorry if I've mistakenly offended you. The problem is that people tend to see open source developers as their unpaid IT department, and your wording triggered this reaction (and even after review, I still feel that it is well-worded). In Germany we have two proverbs "der Ton macht die Musik" (translates to: the sound makes the music; meaning: it's not what you say, but how you say it) and "wie man in den Wald hineinruft, so schallt es heraus" (the way you shout in the woods, the way it is returned; what goes around, comes around). I invested my time your problem and the reply was "I already have solutions, it's one line in a script, but I'm still 'annoyed', make it work. It works with other packages". I'm not a native English speaker either, but if you want other people to invest time into their voluntary work you are using, stating that you are "annoyed" or "bored" by a minor issue obviously nobody had in the years the software is available, isn't the way to go.

However, I'm not the one to hold a grudge, and I agree that inheriting the ACLs from `/tmp` might be the issue, as mentioned above:

> Maybe you're system inherits the access rights from `/tmp`?

**Comment by finalspy** [comment]
To clarify and make a reproducible example I've setup this quick [project](https://github.com/finalspy/openxlsx333), the [docker image](https://hub.docker.com/repository/docker/finalspy/openxlsx333) is also publicly available. 

I'll use this above project/images to test and try to find a way to get around this issue.

**Comment by finalspy** [comment]
Hi @JanMarvin sorry to bother you, but do you know how the releases are scheduled ? 
Will we have a 4.2.6 or 4.3 ... relatively soon ? If no or you don't know it's fine for me. 
(and yes I know I can build my self etc. but the people using the lib prefers to rely on an "official" release and asked me when it will be available so I'll let them know official answer and give them the opportunity to choose between two options )

**Comment by JanMarvin** [comment]
Sorry, no clue. Only @ycphs can answer this, I'm just a contributor here myself. There are a few commits in development already, but I doubt anyone is actively testing them. You could ship internal development builds with drat for instance if you need binaries earlier? (Not sure about the r-universe, @ycphs has set up for the repo. Maybe they ship branches as well. Might be worth looking into.)
