### ISSUE TITLE
addition of more than one conditionalFormatting() function corrupts the Excel file

### ISSUE THREAD

**Issue by omertayyab** [ycphs/openxlsx#351]
I'm using conditional formatting to create databars on some columns.
When I apply it to a single column and save the workbook, it works well and the workbook is saved fine and opens up in Excel.
When I apply it to multiple columns, the workbook saves but upon opening in Excel, I get the following message:

"We found a problem with some content in 'LFS_data.xlsx'. Do you want us to recover as much as we can? If you trust the source of the workbook, click Yes"
When I click yes, it gives me an error log, which is copied below:

```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error152400_01.xml</logFileName>
<summary>Errors were detected in file 'C:\GitlabRepos\LFS_data.xlsx'</summary>
-<removedParts>
<removedPart>Replaced Part: /xl/worksheets/sheet3.xml part with XML error. Load error. Line 14, column 0.</removedPart>
</removedParts>
</recoveryLog>

```

I'm using the following code:
```
wb <- loadWorkbook(paste0(dir_local,"LFS_data.xlsx"))
writeData(wb, sheet = "SC_adjusted_1976", wid[-2], colNames = FALSE, startRow = 5) # if colnames=TRUE, startRow =4
writeData(wb, sheet = "SA_2", basedef, colNames = FALSE, startRow = 1, startCol = length(result))
writeData(wb, sheet = "SA_2", result, colNames = TRUE, startRow = 2)
conditionalFormatting(wb,sheet="SA_2",cols=length(result)-1 ,rows=6:20, type="databar")
conditionalFormatting(wb,sheet="SA_2",cols=length(result) ,rows=6:20, type="databar")
saveWorkbook(wb,paste0(dir_local,"LFS_data.xlsx"),overwrite = TRUE)
```

**Comment by JanMarvin** [comment]
This is indeed a bug. It can be reproduced using:

```R
library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, "databar")

## Databars
writeData(wb, "databar", -5:5, startCol = 1)
conditionalFormatting(wb, "databar", cols = 1, rows = 1:11, type = "databar") ## Defaults

writeData(wb, "databar", -5:5, startCol = 3)
conditionalFormatting(wb, "databar", cols = 3, rows = 1:11, type = "databar", border = FALSE)
```

Out extLst looks like this (two ext nodes):
```XML
<ext uri="{78C0D931-6437-407d-A8EE-F0AAD7539E65}" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
 <x14:conditionalFormattings>
  <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
  ...
  </x14:conditionalFormatting>
 </x14:conditionalFormattings>
</ext>
<ext uri="{78C0D931-6437-407d-A8EE-F0AAD7539E65}" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
 <x14:conditionalFormattings>
  <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
   ...
  </x14:conditionalFormatting>
 </x14:conditionalFormattings>
</ext>
```

In Excel it looks like this (one ext node with two conditional formatting inside conditional formattings:
```XML
<ext uri="{78C0D931-6437-407d-A8EE-F0AAD7539E65}" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
 <x14:conditionalFormattings>
  <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
  ...
  </x14:conditionalFormatting>
  <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
   ...
  </x14:conditionalFormatting>
 </x14:conditionalFormattings>
</ext>
```

Most likely somebody who did not understand what was going on (me), has introduced this bug.

**Comment by JanMarvin** [comment]
I've fixed this in openxlsx2, but my fix is not easily backwards compatible, because it requires merging two `extLst`s. Due to time constraints I wont work on this any further. Until someone picks this up, I'm afraid it will be a wontfix

**Comment by omertayyab** [comment]
Thanks @JanMarvin, I'll try to take it from here, I don't have any experience in XML but this might be a good intro. Cheers!

**Comment by arodionoff** [comment]
I've been struggling with this problem with **some databars** on one page since using MS Excel 2016 and later versions. On earlier versions, for example, MS Excel 2013, **this problem was not found**. Moreover, if you open and immediately save a file with several databars on one page, then the resaved file opens perfectly in new versions of MS Excel.

If you open a file with several databars on one page online in **Google Drive** using Google Table or AppSheet, then the files are opened, but the conditional formatting of the databar is not visible, and if the files are saved to Google Drive, you can open them in new versions of MS Excel just after **AppSheet**, but without _databar conditional formatting_. But the file imported from Google Table cannot even open.

**Comment by JanMarvin** [comment]
Maybe it's a regression (mostly on our end), but fixing it would require a lot of work in `openxlsx`. The issue is, if I recall correctly, that multiple `extLst` or `ext` nodes are attached below the data part in the output XLSX. If all you need is databars, have a look at [the conditional formatting vignette of openxlsx2](https://janmarvin.github.io/openxlsx2/articles/conditional-formatting.html), where it works flawlessly. There's still an open issue, where loading a databar and adding a new one on top does not yet work, but that will be fixed soon.
