### ISSUE TITLE
Inline formatting of text within a cell

### ISSUE THREAD

**Issue by khorovatin** [ycphs/openxlsx#46]
**Is your feature request related to a problem? Please describe.**
I'm using openxlsx to create an Excel workbook that has an introduction and instructions in a large merged cell on the first worksheet in the workbook. I currently have to manually format parts of the text after the workbook has been created.

**Describe the solution you'd like**
I'd like to be able to write text with inline character formatting (e.g., size, color, font type, weight, etc.). The approach taken for Comments, although not perfect for my needs, would be useful.

**Describe alternatives you've considered**
I haven't found a way to do this other than manually after the workbook has been saved.

**Additional context**
![image](https://user-images.githubusercontent.com/9775649/75197919-9a70b580-571c-11ea-9c53-8ede8fca79ef.png)

**Comment by ycphs** [comment]
Thank you for the idea. I agree it would be beneficial to have this features.

**Comment by ycphs** [comment]
Can you try to implement it and create a pull request?

**Comment by khorovatin** [comment]
I'm not much of a programmer, but I will give it a try.

**Comment by Arthfael** [comment]
This would be fantastic. I missed this post and posted a similar issue now almost a year ago. Since then, I have used an Excel macro to perform the task, but it would be fantastic if it could be done directly by the package.

**Comment by FolkyHobbit** [comment]
This would be great. an other Issue #98, which I think is a duplicate, mentioned the possibility to work with html tags, also markdown tags could do the job I think, though I think there is no markdown tag for font color. I do not know which approach would be easier to implement and I think I could work with both a tag based approach or the approach taken for Comments.

**Comment by FolkyHobbit** [comment]
> 
> 
> This would be fantastic. I missed this post and posted a similar issue now almost a year ago. Since then, I have used an Excel macro to perform the task, but it would be fantastic if it could be done directly by the package.

I would be interested in your excel macro if you would be willing to share... could be a good workaround for now..

**Comment by Arthfael** [comment]
It was created by my technician, I got his consent to share it. You can
download it from: *https://we.tl/t-iftXUrBS5R <https://we.tl/t-iftXUrBS5R>*
(I couldn't attach the whole thing directly here because Google doesn't
allow macros for security reasons)
It takes as input a tables of protein sequences and matching peptide ids,
and another table of peptide ids and their sequences, and colours in green
for each protein the part of the sequence matched by the peptides.

Example R code (overly complicated), so you can make sense of the many
arguments and dig into the code to where the actual formatting takes place.

# Prepare data
## Temporary proteins table
temp1 <- data.frame(Accession = PG$"Protein ID",
                    `Peptide IDs` = PG2$"Peptide IDs",
                    check.names = FALSE)
temp1$Sequence <- db$Sequence[match(temp1$Accession, db$"Protein ID")]
write.csv(temp1, file = "temp1.csv", row.names = FALSE)
## Temporary peptides table
temp2 <- data.frame(ID = pep$id, Sequence = pep$Sequence)
write.csv(temp2, file = "temp2.csv", row.names = FALSE)
#
path <- ... # Enter here the location where the macro's VBS and VBA files
were saved
wd <- getwd() # Location where temp1 and 2 were saved
sheetnm <- ... # Name of the sheet in which to apply formatting
if ("1st accession sequence coverage (peptides)" %in% wrcol[[sheetnm]]) {
  cmd <- paste0("WScript \"", path,
"\\aRmel\\data\\sequ_color_only_VBS.vbs\" ", #full path of vbaFromVbs.vbs
                "/fpathXlsm:\"", path,
"\\aRmel\\data\\sequ_color_only_VBA.xlsm\" ", #full path of
SequColorVBA.xlsm
                "/fpathPeptides:\"", wd, "\\Tables\\temp2.csv\" ",
#fullpath of temp2 (peptides)
                "/fpathProt:\"", wd, "\\temp1.csv\" ", #fullpath of temp1
(proteins)
                "/fpathGrps:\"", wd, "\\proteinGroups.xlsx\" ", #fullpath
of proteins xlsx file
                "/shGrps:\"", sheetnm, "\" ", #sheet name within proteins
xlsx file
                "/colPepID:\"ID\" ", #col name of peptide IDs in temp2
                "/colPepSequ:\"Sequence\" ", #col name of peptide sequence
in temp2
                "/colProtAcc:\"Accession\" ", #col name of Accession No.
                "/colProtPepIDs:\"Peptide IDs\" ", #col name of list of
peptide IDs in temp1
                "/colProtSequ:\"Sequence\" ", #col name of protein sequence
in temp1
                "/colGrpsProtIDs:\"Protein IDs\" ", #col name of ids in target
sheet of proteins xlsx file
                "/colGrpsSequ:\"1st accession sequence coverage
(peptides)\" ", # Target (empty) column in target sheet of proteins xlsx
file
                "/HeaderRow:\"", 1, "\" ", #row of header in
proteinGroups.xlsx
                "/StartDataRow:\"", 3, "\" " #first row of data in
proteinGroups.xlsx
  )
  #message(cmd) #(if you need to inspect the final command)
  system(cmd, wait = TRUE)
}
unlink(paste0(wd, "/temp1.csv"))
unlink(paste0(wd, "/temp2.csv"))



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_2385058224670435395_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by khorovatin** [comment]
Hi Arthfael,

I missed your message when it first was posted and now the link to your macro has expired. Would you mind posting a new link?

Thanks

**Comment by Arthfael** [comment]
Sure, here you go!
https://we.tl/t-xvYoZ29EDK
Cheers,

Armel

**Comment by JanMarvin** [comment]
Just because I came across this and remembered the issue: You need to find the text in the sharedStrings table and create something like this:

```xml
<si>
  <r>
    <t>Plain Text -</t>
  </r>
  <r>
    <rPr>
       <sz val="11"/>
       <color rgb="FFFF0000"/>
       <rFont val="Calibri"/>
       <family val="2"/>
       <scheme val="minor"/>
     </rPr>
     <t>Fancy Text</t>
  </r>
</si>
```

This will be the value of a single cell. Whenever somethings highlighted you need the `<r><rPr>...</rPr><t>...</t></r>` block. Ideally you find your sharedString entry in the sharedStrings table (something like `wb$sharedStrings`). Modify it and/or replace it. The tricky part is identifying what options `<rPr>` needs ... oh and yes string manipulation in R is also ... interesting.

[Edit:] Another addition to this: the entire Run Properties for the rich text node (the r node next to the rPr node in the example above) can be found here: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.runproperties?view=openxml-2.8.1

**Comment by khorovatin** [comment]
I have been working on other projects and have not needed this functionality recently, but when I return to the original project I would like to be able to do inline formatting.

**Comment by Arthfael** [comment]
Sorry to bother everyone, but I think recently added issue #422 is a duplicate. Which goes to show that it would be great to have such a feature as it has already been requested by at least 4 different persons.
