### ISSUE TITLE
refactor to use cpp11?

### ISSUE THREAD

**Issue by pachadotdev** [ycphs/openxlsx#513]
Is there any interest in moving from Rcpp to cpp11?

I could do that, I have been using my own fork of openxlsx to summarise tons of data into accessible spreadsheets in a server with restrictions and no direct internet connection. In that way, I can use vendoring to make the package 100% self-contained and dependency-free besides common packages authorised by IT.

**Comment by JanMarvin** [comment]
Hi @pachadotdev , thanks for reaching out, but I'm sorry, as the current maintainer I'm not interested. So unless you want to maintain it in your own fork, working on it would be a waste of time. I maintain `openxlsx` basically just to keep the package on CRAN - as a service to the many packages and tons of legacy code that still depend on it. And I understand that in certain environments it's not possible to install packages without IT's blessing, but `Rcpp` is probably not the dependency I'd worry about. If IT won't allow `Rcpp`, then hopefully they won't allow the hacky C++ code of `openxlsx` either. 😉 

Apart from that, it looks from the outside as if `cpp11` is a bit abandoned since Jim Hesters departure, but I haven't spent much time looking into it.

**Comment by pachadotdev** [comment]
> Hi @pachadotdev , thanks for reaching out, but I'm sorry, as the current maintainer I'm not interested. So unless you want to maintain it in your own fork, working on it would be a waste of time. I maintain `openxlsx` basically just to keep the package on CRAN - as a service to the many packages and tons of legacy code that still depend on it. And I understand that in certain environments it's not possible to install packages without IT's blessing, but `Rcpp` is probably not the dependency I'd worry about. If IT won't allow `Rcpp`, then hopefully they won't allow the hacky C++ code of `openxlsx` either. 😉
> 
> Apart from that, it looks from the outside as if `cpp11` is a bit abandoned since Jim Hesters departure, but I haven't spent much time looking into it.

good point! I got a reprimand a while ago for using non-ISO conventions in my own code

**Comment by pachadotdev** [comment]
Davis Vaughan seems to be an active cpp11 maintainer :)

**Comment by JanMarvin** [comment]
Thanks for understanding. I didn't want to put anybodies work down and like I've said, I haven't really looked into it.
