### ISSUE TITLE
Allow the user to define individual column  types when reading a file

### ISSUE THREAD

**Issue by tkpmep** [ycphs/openxlsx#88]
I would like to be able to specify column types when reading a file, e.g.
df  <- read_excel(fn, sheet = "Sheet1", range = cell_cols("A:E"), col_types = c("text", "date", "date", "numeric", "numeric"))

I'm currently using readxl to do just this when reading a file, and use openxlsx when writing files. I'd like to be able to use openxlsx for both reading and writing. Would you kindly add this to the list of requested features?

Many thanks in advance

Thomas Philips

**Comment by ycphs** [comment]
Hi,

I understand the request. Currently only the the flag `detectDates ` is supported.

It would be great to have this feature. Could you provide a pull request?

**Comment by tkpmep** [comment]
I only wish I knew what a pull request was...., but if you could point me in the right direction, I would be delighted to do it.

**Comment by ycphs** [comment]
Hi,

Wouldn't it be more beneficial to do the type conversion after getting the data to R?

**Comment by tkpmep** [comment]
I’d much rather it be done cleanly at the start so that I don’t have to deal with type conversion and cleanup later. Some things will be ambiguous  (which is likely why dates is a specified column type) – it’s much better to be able to specify what to expect, and to make anything that falls outside these guidelines an NA.

**Comment by avsdev-cw** [comment]
I too would like to see this. It is especially important when ingesting a number of xls files in a loop (e.g. lapply) and then rbind'ing them. If the data is sparse the parser can sometimes interpret columns with different types rendering the rbind incapable of combining the resulting data frames (e.g. double & char is a common one I run into). Specifying the type to load would solve this issue at source.

**Comment by JanMarvin** [comment]
Well this is a non-trivial thing to ask, if you want the actual import from xlsx files to function this way. For starters, someone has to (i) begin with understanding the current code and (ii) modify it to retain the current behavior and (iii) implement the new. I can guarantee you, that (i) alone is a burden for many people.

Since the data is stored inside an xml file as a bunch of characters - you do not actually lose precision or something alike by not importing it as numeric in the first place - why don't you start by writing a modification on the R level for the `read.xlsx.default` function. As suggested (make a fork of this repo and create a branch) write a loop or an lapply over a character vector switching things to the wanted types. Something like:

```R
read.xlsx.default <- function( ..., as = c("numeric", "character")) {
   ...
   if (!missing(as)) {
    for (a in as) {
     if (a == "character") data <- as.character(data)
     if (a == "numeric) data <- as.numeric(data)
    }
}
```

Finally, create a commit and push it. Once that is done, open a pull request and someone can review it to give further guidance or it might simply be merged and be part of the new release. After all that is the beauty of open source code, you can actually change things (you want or need) and do not have to rely on someone else to do it for you.

**Comment by tkpmep** [comment]
I’ll speak for myself and say that my programming skills are sufficiently poor that I would hate to have the world rely on a function I edited, certainly for low level stuff like this. Question: Isn’t Openxlsx maintained by a team that knows the code?

**Comment by JanMarvin** [comment]
It's not that I'm saying that no one knows the code, but if you're coming back to code you've written before, you still have to understand what is going on.
All I'm saying is, I'd be willing to help you, if you're going to implement this feature. My few lines drafted above should give you a hint, where to start. Apparently no one else is in dire need of the feature or has had the time to implement it.
