### ISSUE TITLE
Creating pivot tables

### ISSUE THREAD

**Issue by klar-C** [ycphs/openxlsx#95]
Hi,

It would be great if one could create actual pivot tables in the Excel sheet (including selection of fields / aggregation / filters). I know in theory I could aggregate it in R and then create the output, but there's value in being able to change the settings/filters within Excel after the generation.

Is that something that's planned or is it always going to be beyond the scope of this package?

Great package!

Regards,
Christian

**Comment by JanMarvin** [comment]
I might give it a shot on a rainy day (maybe even later today) since sadly pivot tables are part of my everyday job. Though I'm not sure how complex the task is nor if it is feasible at all. Most likely it won't be something we can use from the R side of things (e.g., even if we can create something Excel/Libreoffice/Google sheets etc will interpret as pivot tables, we won't be able to work with actual pivot cell values, since these are depending on the evaluation by the third party software).

Therefore it's kinda interesting and a well designed user API could be beneficial, but it has the tendency to easily become complex and be much more work related than a fun coding thing.
